
apiVersion: v1
kind: ConfigMap
metadata:
  name: inway-service-config
  namespace: nlx-inway
data:
  service-config.toml: |
    [services]
    # This block defines an API exposed by this inway.
    # A single inway can expose multiple API's, therefore this block can be added multiple times.
    # The name of the API must be unique for each block.
      [services.ac]

      # `endpoint-url` should be set to the address at which the API is available.
      endpoint-url = "https://autorisaties-api.vng.cloud/api/v1/"

      # `documentation-url` should point to the documentation for the API
      documentation-url = "https://autorisaties-api.vng.cloud/"

      # `authorization-model` can or whitelist
      authorization-model = "none"

      # `api-specification-document-url` defines the specification document for the API
      api-specification-document-url = "https://autorisaties-api.vng.cloud/api/v1/schema/"

      # `public-support-contact` contains an email address which NLX users can contact if they need support using your API.
      # This email address is published in the directory.
      # this field is optional
      # public-support-contact = "support@my-organization.nl"

      # `tech-support-contact` contains an email address which we (the NLX organization) can contact if they have any questions about your API
      # This email address will NOT be published in the directory
      # this field is optional
      # tech-support-contact   = "tech@my-organization.nl"
      [services.brc]
      endpoint-url = "https://besluiten-api.vng.cloud/api/v1/"
      documentation-url = "https://besluiten-api.vng.cloud/"
      authorization-model = "none"
      api-specification-document-url = "https://besluiten-api.vng.cloud/api/v1/schema/"
      [services.drc]
      endpoint-url = "https://documenten-api.vng.cloud/api/v1/"
      documentation-url = "https://documenten-api.vng.cloud/"
      authorization-model = "none"
      api-specification-document-url = "https://documenten-api.vng.cloud/api/v1/schema/"
      [services.nrc]
      endpoint-url = "https://notificaties-api.vng.cloud/api/v1/"
      documentation-url = "https://notificaties-api.vng.cloud/"
      authorization-model = "none"
      api-specification-document-url = "https://notificaties-api.vng.cloud/api/v1/schema/"
      [services.zrc]
      endpoint-url = "https://zaken-api.vng.cloud/api/v1"
      documentation-url = "https://zaken-api.vng.cloud/"
      authorization-model = "none"
      api-specification-document-url = "https://zaken-api.vng.cloud/api/v1/schema/"
      [services.ztc]
      endpoint-url = "https://catalogi-api.vng.cloud/api/v1/"
      documentation-url = "https://catalogi-api.vng.cloud"
      authorization-model = "none"
      api-specification-document-url = "https://catalogi-api.vng.cloud/api/v1/schema/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inway-service-rootca
  namespace: nlx-inway
data:
  root.crt: | 
    -----BEGIN CERTIFICATE-----
    MIIFjjCCA3agAwIBAgIUETfEQ3CBxDQoa7TxaXlDzNHOFbowDQYJKoZIhvcNAQEN
    BQAwXzELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNV
    BAcTCUFtc3RlcmRhbTEWMBQGA1UEChMNQ29tbW9uIEdyb3VuZDEMMAoGA1UECxMD
    TkxYMB4XDTE4MDIyMzExMTkwMFoXDTIzMDIyMjExMTkwMFowXzELMAkGA1UEBhMC
    TkwxFjAUBgNVBAgTDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcTCUFtc3RlcmRhbTEW
    MBQGA1UEChMNQ29tbW9uIEdyb3VuZDEMMAoGA1UECxMDTkxYMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEA1hyosh5cOJZTvclIayyjTXqQQmLwTXKy4Ub1
    4rRgctPUc9C4JsXRxg1TPTWSMY66f0WPWsrh+nRKrSvHh+dY7tdye9fKCbmM4CnT
    GQS9ckmHU9i8eUHzv53tjkfZuA5fiuoEcSHx9aaOu/8DVvhix0XGzK5LRUkz/iCY
    gNo1f/uXyel9B50je9La67xERfXtd8zN4vNryB/wQn4C6ERDW/npREM0Geapuo45
    FojXbtseEPiDe/6iQwPaS1rcQzJFTzStA31frxF8wPb30XuoCZimbm3gyQSuBn0u
    fSgclOH0tZUXeJIdPbs6fbTnWeAedItwIkAlnKF5UUrNg9hqVE6/tSPIvIHra1F0
    zrc/1UL9EMdp59vnO7viYIpzAs5sBEQU1wmxK+xU05iBj0LiMo5tX6eT6tem/n7q
    k8FIYt5Iy0kgMT6k7TmJ/H4dualEELffk/+ATXonSX8auipS1aUBUM2tpfn/kxFM
    m4CvCv5Gt2/3/M2DFH/EN+hCHldQYMbBoHlCFh3Co6s4rJf5Im0lSIu2R1dS5k5I
    Yq4m5qhzlUgoQptAywhp6PVhSLPb1iL0cU8wSHlA2v3Pr5zVgH5HNt0xcyh/mECY
    BIeNMnuIoHkg62t218YyTwioXjjDVRnxtzPOoGm52Zb9v0cmbzSf/mrcC2Gx9SOj
    9M3yzj8CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8w
    HQYDVR0OBBYEFFrgQVERh6zaaIfAAMMGXOJ5LYn9MA0GCSqGSIb3DQEBDQUAA4IC
    AQAER3nogPn9weENdFDM0WbXFmQEMdJc1rppKYqTYSj/SSLI6vGK6i/PgrSmGy6N
    9dgJnHPWvqffyfXISsZpUE0zWaMqrIHLvk+yxhhAFxYuLWIr7li8XE73dBfPS0An
    y76rTbYQJuglLtnCl3urOvuLubzEFKYkVp3esmQnx/2tiarnT7RZq4RUM+4qf4jg
    fJFJqxC7Yk1re88cOgW1VKuMkdKuFrHgd34qIn/haN3AuEcGwvMRXb1BrHuJuIsP
    +8fb8VwLHuAe8d0vVgn99Dh1lGzAMeDVzaZSYMZb/YnuZ2GYOzZAH9bA0LYdNYGg
    LpiGDkoJvWqPKZgC4C8ucy8H8meVp6koVRa1/Edm8rmEEvOE3xDZAGtHNg/NAedx
    RBp8u4ujHMdpBb2XO0R4djzIm0iRFa3AB0OwQP7/Oln3paJf5lh8EdEtCpGRxOGd
    XjA+LiNx9tWoi/wsE7xil02wwi7jgznJEf5U26WLhhmpP3/s24KOarJcXkUFvOgY
    AxBiKxa0IvQBkDWJb0OnP8SVpoltjKtNQOAGF7ngzHB0SkJlsAQspiTOBS1YeZ+4
    4rGOiVIygm2313ofR8kPSFVLEGyW73TkZdj9ZR8vQuGXjEqNVUd9GHWhft3142co
    vKZ0d7BYa5Tc7mjzUomFPYM8BQQQqClyABHXf0lMwRKn6Q==
    -----END CERTIFICATE-----
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: inway-service-rootca
        - name: inway-service-config
          configMap:
            name: inway-service-config
      containers:
        - name: inway
          image: nlxio/inway:v1.0.0
          imagePullPolicy: Always
          env:
            - name: LOG_TYPE
              value: local
            - name: LOG_LEVEL
              value: debug
            - name: TLS_NLX_ROOT_CERT
              value: /certs/root.crt
            - name: TLS_ORG_CERT
              value: TODO
            - name: TLS_ORG_KEY
              value: TODO
            - name: DISABLE_LOGDB
              value: "true"
            - name: SELF_ADDRESS
              value: https://zaakgerichtwerken-inway.vng.cloud/
            - name: DIRECTORY_REGISTRATION_ADDRESS
              value: "directory-registration-api.demo.nlx.io:443"
            - name: SERVICE_CONFIG
              value: /inway-service-config/service-config.toml
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: inway-service-config
              mountPath: /inway-service-config
      restartPolicy: Always
  status: {}
