# Example 1: Exact match - only these rules should trigger
openapi: 3.0.0
info:
  title: Test API
x-tools-validator:
  id: test-1
  spectral:
    matches:
      - oas3-schema
      - info-contact
      - info-description
      - oas3-api-servers
  zgw-cleaner:
    cleaned-id: test-2
---
# Example 2: Including - these rules must trigger (others may too)
openapi: 3.0.0
info:
  title: Test API
x-tools-validator:
  id: test-2
  spectral:
    including:
      - info-contact
    excluding:
      - info-contact
---
# Example 3: Excluding - these rules must not trigger
openapi: 3.0.0
info:
  title: Test API
x-tools-validator:
  id: test-3
  spectral:
    excluding:
      - operation-tags-alphabetical
---
# Example 4: No spectral config - ignore all rules
openapi: 3.0.0
info:
  title: Test API
x-tools-validator:
  id: test-4
