extends:
  - ./tools/spectral/adr_kpa_corrected.yaml
  # - ./tools/spectral/adr_kpa.yaml
  # - ./tools/spectral/adr_don.yaml
  # - ./tools/spectral/adr_don_corrected.yaml
  # - ./tools/spectral/zgw-api-design-rules.yaml  