extends:
  # - ["spectral:oas", "off"] # extend spectral:oas maar niet standaard alle regels
  # - [tools/spectral/adr-2.1.0-logius.yaml, off]
  - tools/spectral/adr-2.1.0-logius-truth.yaml

# rules:
#   # /core/publish-openapi (deze error-rules valideren of OAS valid is)
#   oas3-schema: true
#   operation-operationId-unique: true
#   path-params: true
#   openapi-tags-uniqueness: true
#   oas3-valid-media-example: true
#   oas3-valid-schema-example: true
#   oas3-server-variables: true

#   # deze stond er al in, maar is niet direct gekoppeld aan een ADR
#   oas3-api-servers: error