# Spectral configuratie voor API specificaties
#
# De Nederlandse API Design Rules zijn gebaseerd op de Logius standaard:
# https://gitdocumentatie.logius.nl/publicatie/api/adr/
#
# De onderstaande rulesets breiden de Nederlandse API Design Rules uit met
# regels die specifiek zijn voor de ZGW API's.
#
# Gebruik: spectral lint pad/naar/uw/openapi.yaml

extends:
  - ./rulesets/nlgov_api_design_rules.yaml
  - ./rulesets/zgw_composition_rules.yaml
  - ./rulesets/zgw_polymorphism_rules.yaml
