/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gidsSidebar: [
    {
      type: "autogenerated",
      dirName: "gids",
    },
  ],
  apiSidebar: [
    { type: "doc", id: "api-suite/index" },
    { type: "doc", id: "api-suite/intro" },
    // { type: "autogenerated", dirName: "." },

    {
      type: "category",
      label: "API's",
      link: {
        type: "generated-index",
        title: "API Referentie",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/api-reference",
      },
      items: [
        {
          type: "category",
          label: "Autorisaties API",
          link: {
            type: "generated-index",
            title: "Autorisaties API",
            description:
              "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
            slug: "/category/autorisaties-api",
          },
          items: require("../docs/v1/api-suite/autorisaties/sidebar.js"),
        },
      ],
    },
  ],
  //   openApiSidebar: [
  //     { type: "doc", id: "api_overview"},
  //     {
  //       type: "category",
  //       label: "Besluiten API",
  //       link: {
  //         type: "generated-index",
  //         title: "Besluiten API",
  //         description:
  //           "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //         slug: "/category/besluiten-api"
  //       },
  //       items: require("./docs/besluiten/sidebar.js")
  //     },
  //     {
  //       type: "category",
  //       label: "Catalogi API",
  //       link: {
  //         type: "generated-index",
  //         title: "Zaaktypecatalogi API",
  //         description:
  //           "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //         slug: "/category/catalogi-api"
  //       },
  //       items: require("./docs/catalogi/sidebar.js")
  //     },
  //     {
  //       type: "category",
  //       label: "Documenten API",
  //       link: {
  //         type: "generated-index",
  //         title: "Documenten API",
  //         description:
  //           "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //         slug: "/category/documenten-api"
  //       },
  //       items: require("./docs/documenten/sidebar.js")
  //     },
  //     {
  //       type: "category",
  //       label: "Notificaties API",
  //       link: {
  //         type: "generated-index",
  //         title: "Notificaties API",
  //         description:
  //           "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //         slug: "/category/documenten-api"
  //       },
  //       items: require("./docs/notificaties/sidebar.js")
  //     },
  //     {
  //       type: "category",
  //       label: "Zaken API",
  //       link: {
  //         type: "generated-index",
  //         title: "Zaken API",
  //         description:
  //           "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //         slug: "/category/zaken-api"
  //       },
  //       items: require("./docs/zaken/sidebar.js")
  //     }
  //   ]
};

export default sidebars;
