/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gidsSidebar: [
    {
      type: "autogenerated",
      dirName: "gids",
    },
  ],
  apiSidebar: [
    { type: "doc", id: "api-suite/index" },
    { type: "doc", id: "api-suite/intro" },
    {
      type: "category",
      label: "Autorisaties API",
      link: {
        type: "generated-index",
        title: "Autorisaties API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/autorisaties-api",
      },
      items: require("../docs/v1/api-suite/autorisaties/sidebar.js"),
    },
    {
      type: "category",
      label: "Besluiten API",
      link: {
        type: "generated-index",
        title: "Besluiten API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/besluiten-api",
      },
      items: require("../docs/v1/api-suite/besluiten/sidebar.js"),
    },
    {
      type: "category",
      label: "Documenten API",
      link: {
        type: "generated-index",
        title: "Documenten API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/documenten-api",
      },
      items: require("../docs/v1/api-suite/documenten/sidebar.js"),
    },
    // {
    //   type: "category",
    //   label: "Zaken API",
    //   link: {
    //     type: "generated-index",
    //     title: "Zaken API",
    //     description:
    //       "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
    //     slug: "/category/zaken-api",
    //   },
    //   items: require("../docs/v1/api-suite/zaken/sidebar.js"),
    // },
    // {
    //   type: "category",
    //   label: "Catalogi API",
    //   link: {
    //     type: "generated-index",
    //     title: "Catalogi API",
    //     description:
    //       "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
    //     slug: "/category/catalogi-api",
    //   },
    //   items: require("../docs/v1/api-suite/catalogi/sidebar.js"),
    // },
  ]
};

export default sidebars;
