# # frozen_string_literal: true

# source "https://rubygems.org"

# # gem "rails"

# gem "jekyll", "~> 4.4"

# gem "jekyll-redirect-from", "~> 0.16.0"

# gem "jekyll-remote-theme", "~> 0.4.3"

# gem "webrick", "~> 1.8"

# cd /home/henri_k/github/vng/gemma-zaken/docs
# bundle exec jekyll serve --livereload

gem "github-pages", group: :jekyll_plugins